platform :ios,'8.0'
target 'cycleLife' do
pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 4.0.0'
pod 'YYImage', '~> 1.0.4'
end